
export const LANGUAGES = {
  EN: 'en',
  AR: 'ar',
  FR: 'fr'
};

export const UI_STRINGS: Record<string, any> = {
  en: {
    appTitle: "NutriAI",
    welcome: "Welcome back",
    hello: "Hello",
    trackProgress: "Track your progress for today",
    todayIntake: "Today's Intake",
    kcalRemaining: "kcal remaining",
    scanFood: "Scan Product",
    analyzeRecipe: "Analyze Recipe",
    weeklyCalories: "Weekly Calories",
    recentItems: "Recent Items",
    noItemsToday: "No items yet today. Start analyzing!",
    recipeBook: "Collection",
    profile: "Profile",
    medicalAi: "Medical AI",
    nearby: "Nearby Healthy",
    home: "Home",
    calories: "Calories",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
    sugar: "Sugar",
    healthScore: "Health Score",
    benefits: "Health Benefits",
    risks: "Health Risks",
    alternatives: "Better Alternatives",
    saveToBook: "Save to Book",
    addToLog: "Add to Log",
    tips: "Preparation Tips",
    medicalAdviceTitle: "Medical Consultant",
    medicalAdvicePlaceholder: "Ask about your health condition or diet...",
    language: "Language",
    upgrade: "Upgrade Plan",
    scansRemaining: "Scans left",
    servings: "servings",
    ingredients: "Ingredients",
    recipeName: "Recipe Name",
    calculate: "Calculate Nutrition",
    positionFrame: "Position food product inside the frame",
    aiAnalyzing: "AI is Analyzing...",
    enhancingImage: "Enhancing image, OCRing labels, and calculating nutrition...",
    scanLabelHint: "Upload a photo of the nutrition label or ingredients for best results.",
    whyAnalyzeTitle: "Why analyze recipes?",
    whyAnalyzeDesc: "NutriAI goes beyond scanning labels. Input home-cooked meals for a complete picture and get healthy tips.",
    collectionTitle: "Recipe Book",
    collectionSub: "Your personal healthy collection",
    noRecipes: "No recipes saved yet",
    saveRecipeHint: "Analyze a custom recipe and save it to see it here!",
    proTip: "Pro Tip",
    proTipDesc: "Consistent tracking leads to 2x faster goal achievement.",
    healthierSwaps: "Healthier Swaps",
    aiInsights: "AI Insights",
    cookingTips: "Cooking Tips",
    savedToCollection: "Saved to Collection",
    numServings: "Number of Servings",
    findingNearby: "Finding healthy spots nearby...",
    locationError: "Could not access location",
    nearbyHealthyPlaces: "Nearby Healthy Places"
  },
  ar: {
    appTitle: "نوتري آي",
    welcome: "مرحباً بك",
    hello: "أهلاً",
    trackProgress: "تتبع تقدمك لهذا اليوم",
    todayIntake: "تناول اليوم",
    kcalRemaining: "سعرة متبقية",
    scanFood: "مسح منتج",
    analyzeRecipe: "تحليل وصفة",
    weeklyCalories: "سعرات الأسبوع",
    recentItems: "العناصر الأخيرة",
    noItemsToday: "لا توجد عناصر اليوم. ابدأ التحليل!",
    recipeBook: "المجموعة",
    profile: "الملف الشخصي",
    medicalAi: "ذكاء طبي",
    nearby: "أماكن صحية",
    home: "الرئيسية",
    calories: "سعرات",
    protein: "بروتين",
    carbs: "كربوهيدرات",
    fat: "دهون",
    sugar: "سكر",
    healthScore: "نقاط الصحة",
    benefits: "الفوائد الصحية",
    risks: "المخاطر الصحية",
    alternatives: "بدائل أفضل",
    saveToBook: "حفظ في الكتاب",
    addToLog: "إضافة للسجل",
    tips: "نصائح التحضير",
    medicalAdviceTitle: "المستشار الطبي",
    medicalAdvicePlaceholder: "اسأل عن حالتك الصحية أو نظامك الغذائي...",
    language: "اللغة",
    upgrade: "ترقية الخطة",
    scansRemaining: "المسحات المتبقية",
    servings: "حصص",
    ingredients: "المكونات",
    recipeName: "اسم الوصفة",
    calculate: "حساب التغذية",
    positionFrame: "ضع المنتج الغذائي داخل الإطار",
    aiAnalyzing: "الذكاء الاصطناعي يحلل...",
    enhancingImage: "تحسين الصورة، قراءة الملصقات، وحساب التغذية...",
    scanLabelHint: "ارفع صورة لملصق التغذية أو المكونات للحصول على أفضل النتائج.",
    whyAnalyzeTitle: "لماذا نحلل الوصفات؟",
    whyAnalyzeDesc: "نوتري آي يتجاوز مجرد مسح الملصقات. أدخل وجباتك المنزلية للحصول على صورة كاملة ونصائح صحية.",
    collectionTitle: "كتاب الوصفات",
    collectionSub: "مجموعتك الصحية الشخصية",
    noRecipes: "لم يتم حفظ أي وصفات بعد",
    saveRecipeHint: "حلل وصفة مخصصة واحفظها لتظهر هنا!",
    proTip: "نصيحة الخبراء",
    proTipDesc: "التتبع المستمر يؤدي إلى تحقيق الأهداف أسرع بمرتين.",
    healthierSwaps: "تبديلات صحية",
    aiInsights: "رؤى الذكاء الاصطناعي",
    cookingTips: "نصائح الطبخ",
    savedToCollection: "تم الحفظ في المجموعة",
    numServings: "عدد الحصص",
    findingNearby: "البحث عن أماكن صحية قريبة...",
    locationError: "تعذر الوصول إلى الموقع",
    nearbyHealthyPlaces: "أماكن صحية قريبة"
  },
  fr: {
    appTitle: "NutriAI",
    welcome: "Bon retour",
    hello: "Bonjour",
    trackProgress: "Suivez vos progrès aujourd'hui",
    todayIntake: "Apport d'aujourd'hui",
    kcalRemaining: "kcal restantes",
    scanFood: "Scanner Produit",
    analyzeRecipe: "Analyser Recette",
    weeklyCalories: "Calories Hebdomadaires",
    recentItems: "Articles Récents",
    noItemsToday: "Rien aujourd'hui. Commencez l'analyse !",
    recipeBook: "Collection",
    profile: "Profil",
    medicalAi: "IA Médicale",
    nearby: "Lieux Sains",
    home: "Accueil",
    calories: "Calories",
    protein: "Protéines",
    carbs: "Glucides",
    fat: "Lipides",
    sugar: "Sucre",
    healthScore: "Score Santé",
    benefits: "Avantages Santé",
    risks: "Risques Santé",
    alternatives: "Meilleures Alternatives",
    saveToBook: "Enregistrer",
    addToLog: "Ajouter au Journal",
    tips: "Conseils de Préparation",
    medicalAdviceTitle: "Consultant Médical",
    medicalAdvicePlaceholder: "Posez des questions sur votre santé...",
    language: "Langue",
    upgrade: "Améliorer Plan",
    scansRemaining: "Scans restants",
    servings: "portions",
    ingredients: "Ingrédients",
    recipeName: "Nom de la Recette",
    calculate: "Calculer Nutrition",
    positionFrame: "Placez le produit dans le cadre",
    aiAnalyzing: "L'IA analyse...",
    enhancingImage: "Amélioration de l'image et calcul de la nutrition...",
    scanLabelHint: "Téléchargez une photo de l'étiquette nutritionnelle pour de meilleurs résultats.",
    whyAnalyzeTitle: "Pourquoi analyser les recettes ?",
    whyAnalyzeDesc: "NutriAI va au-delà du scan. Saisissez vos repas faits maison pour un bilan complet.",
    collectionTitle: "Livre de Recettes",
    collectionSub: "Votre collection saine personnelle",
    noRecipes: "Aucune recette enregistrée",
    saveRecipeHint: "Analysez une recette et enregistrez-la ici !",
    proTip: "Conseil de Pro",
    proTipDesc: "Un suivi constant permet d'atteindre vos objectifs 2x plus vite.",
    healthierSwaps: "Échanges plus sains",
    aiInsights: "Aperçus de l'IA",
    cookingTips: "Conseils de cuisine",
    savedToCollection: "Enregistré dans la collection",
    numServings: "Nombre de portions",
    findingNearby: "Recherche de lieux sains...",
    locationError: "Impossible d'accéder à la position",
    nearbyHealthyPlaces: "Lieux sains à proximité"
  }
};
